version: 2
updates:
# Ignore version updates and only open a PR for security updates!
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "pip"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directory: "/test_requirements.txt"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "pip"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/timesketch/frontend-ng"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 0
# ignore dependencies of the legacy front-end since it is deprecated
  - package-ecosystem: "npm"
    directory: "/timesketch/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

