matrix:
  include:
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    env: [MODE="pypi", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Dockerfile"
    env: [TARGET="dockerfile"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
cache:
- pip
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
