services:
  timesketch-web:
    container_name: timesketch-web
    image: us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:${TIMESKETCH_VERSION}
    environment:
      - NUM_WSGI_WORKERS=${NUM_WSGI_WORKERS}
    restart: always
    command: timesketch-web
    volumes:
      - ${TIMESKETCH_CONFIG_PATH}:/etc/timesketch/
      - ${TIMESKETCH_UPLOAD_PATH}:/usr/share/timesketch/upload/
      - ${TIMESKETCH_LOGS_PATH}:/var/log/timesketch/
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # [DEPRECATED] Add "--profile legacy-ui" to your docker compose command to use the legacy UI
  timesketch-web-legacy:
    container_name: timesketch-web-legacy
    image: us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:${TIMESKETCH_VERSION}
    environment:
      - NUM_WSGI_WORKERS=${NUM_WSGI_WORKERS}
    restart: always
    command: timesketch-web-legacy
    profiles:
      - "legacy-ui"
    volumes:
      - ${TIMESKETCH_CONFIG_PATH}:/etc/timesketch/
      - ${TIMESKETCH_UPLOAD_PATH}:/usr/share/timesketch/upload/
      - ${TIMESKETCH_LOGS_PATH}:/var/log/timesketch/
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # [WIP] Add "--profile v3-ui" to your docker compose command to use the vue3 UI
  timesketch-web-v3:
    container_name: timesketch-web-v3
    image: us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:${TIMESKETCH_VERSION}
    environment:
      - NUM_WSGI_WORKERS=${NUM_WSGI_WORKERS}
    restart: always
    command: timesketch-web-v3
    profiles:
      - "v3-ui"
    volumes:
      - ${TIMESKETCH_CONFIG_PATH}:/etc/timesketch/
      - ${TIMESKETCH_UPLOAD_PATH}:/usr/share/timesketch/upload/
      - ${TIMESKETCH_LOGS_PATH}:/var/log/timesketch/
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  timesketch-worker:
    container_name: timesketch-worker
    image: us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:${TIMESKETCH_VERSION}
    environment:
      - WORKER_LOG_LEVEL=${WORKER_LOG_LEVEL}
    restart: always
    command: timesketch-worker
    volumes:
      - ${TIMESKETCH_CONFIG_PATH}:/etc/timesketch/
      - ${TIMESKETCH_UPLOAD_PATH}:/usr/share/timesketch/upload/
      - ${TIMESKETCH_LOGS_PATH}:/var/log/timesketch/
    depends_on:
      opensearch:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    restart: always
    environment:
      - TAKE_FILE_OWNERSHIP=1
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true" # TODO: Enable when we have migrated the python client to Opensearch as well.
      - "OPENSEARCH_JAVA_OPTS=-Xms${OPENSEARCH_MEM_USE_GB}g -Xmx${OPENSEARCH_MEM_USE_GB}g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${OPENSEARCH_DATA_PATH}:/usr/share/opensearch/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"]
      interval: 10s
      timeout: 10s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=timesketch
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timesketch"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    command: "redis-server"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
    depends_on:
      # Nginx should wait for the web backends to be started.
      - timesketch-web
      - timesketch-web-legacy
      - timesketch-web-v3
