name: e2e-tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - 'README.md'
      - '*.md'

jobs:
  # OpenSearch version 2.x.x
  PyPi-plaso-stable-opensearch-v2:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up infrastructure with docker compose
        run: docker compose -f docker/e2e/docker-compose.yml up -d
        env:
          OPENSEARCH_VERSION: 2.15.0
          PLASO_PPA_TRACK: stable
      - name: Run e2e tests
        run: docker compose -f docker/e2e/docker-compose.yml exec -T timesketch python3 /usr/local/src/timesketch/end_to_end_tests/tools/run_in_container.py
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
