name: linter

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pylint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pylint
        pip install -r test_requirements.txt
        pip install -r requirements.txt
        pip install -e .
        pip install -e api_client/python
        pip install -e importer_client/python
    - name: Run pylint
      run: |
        git config pull.rebase false && git fetch -p origin master
        for FILE in `git --no-pager diff origin/master --name-only | grep \.py$`; do echo "Running pylint against ${FILE}"; pylint --rcfile=.pylintrc ${FILE}; done
  
  eslint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./timesketch/frontend
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn add eslint
    - name: Run eslint
      run: |
        git config pull.rebase false && git fetch -p origin master
        for FILE in `git --no-pager diff origin/master --name-only | grep -e \.vue$ -e \.js$ | grep -v dist\/js | sed s/'^timesketch\/frontend\/'/''/`; do echo "Running eslint against ${FILE}"; yarn run eslint ${FILE}; done
