name: Build and publish Timesketch Docker image

on:
  push:
    branches: ['master']
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-timesketch-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and publish Timesketch Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/release/build
          build-args: |
            BRANCH=${{ github.ref_name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-notebook
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-notebook

      - name: Build and publish Jupyter Labs Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/dev/build
          file: docker/dev/build/Dockerfile-notebook
          build-args: |
            BRANCH=${{ github.head_ref }}
          build-contexts: timesketch_api_client=api_client/
          push: true
          tags: ${{ steps.meta-notebook.outputs.tags }}
          labels: ${{ steps.meta-notebook.outputs.labels }}
