name: unit-tests-frontend

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  yarn:
    defaults:
      run:
        working-directory: timesketch/frontend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: ["12"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          sudo apt install yarn npm --no-install-recommends
          yarn install

      - name: Run unit tests with yarn
        run: yarn run test:unit
