name: ppa unittests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:gift/dev
        sudo apt-get update
        sudo apt-get -y install python3-distutils pylint
        sudo apt-get -y install python3-alembic python3-altair python3-amqp python3-aniso8601 \
            python3-asn1crypto python3-attr python3-bcrypt python3-billiard python3-blinker \
            python3-bs4 python3-celery python3-certifi python3-cffi python3-chardet \
            python3-ciso8601 python3-click python3-cryptography python3-datasketch \
            python3-dateutil python3-editor python3-elasticsearch python3-entrypoints \
            python3-flask python3-flask-bcrypt python3-flask-login python3-flask-migrate \
            python3-flask-restful python3-flask-script python3-flask-sqlalchemy \
            python3-flaskext.wtf python3-google-auth python3-google-auth-oauthlib \
            python3-gunicorn python3-idna python3-itsdangerous python3-jinja2 \
            python3-jsonschema python3-jwt python3-kombu python3-mako python3-mans-to-es \
            python3-markdown python3-markupsafe python3-neo4jrestclient python3-numpy \
            python3-oauthlib python3-pandas python3-parameterized python3-pycparser \
            python3-pyrsistent python3-redis python3-requests python3-requests-oauthlib \
            python3-sigmatools python3-six python3-sqlalchemy python3-tabulate python3-toolz \
            python3-tz python3-urllib3 python3-vine python3-werkzeug python3-wtforms\
            python3-xlrd python3-xmltodict python3-yaml python3-zipp python3-networkx
    - name: Test with unittest
      run: |
        python run_tests.py
